const API_BASE=window.location.hostname.endsWith("github.io")?"https://socce7ball-support.onrender.com":"";
const $=id=>document.getElementById(id); let currentUser=null; let accessToken=localStorage.getItem("socce7ball_access_token")||""; let staffCache=[]; let ticketCache=[]; let blacklistCache=[]; let currentTicket=null; let sending=false; let refreshingMessages=false; let blacklistSearchTimer=null;
async function api(path,options={}){
  const headers={...(options.body?{"Content-Type":"application/json"}:{}),...(accessToken?{"Authorization":"Bearer "+accessToken}:{}),...(options.headers||{})};
  const r=await fetch(API_BASE+path,{credentials:"include",...options,headers});
  if(!r.ok)throw new Error(await r.text());
  return r.json();
}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function setBotImage(url){if(!url)return;["brandBotImage","heroBotImage","sideBotImage","formBotImage","chatBotImage","footerBotImage"].forEach(id=>{const el=$(id);if(el)el.src=url;});}
function showUser(u){
 currentUser=u;setBotImage(u.botAvatar);$("app").classList.remove("hidden");$("loginBtn").innerHTML=(u.avatar?'<img src="'+escapeHtml(u.avatar)+'" alt=""><span>'+escapeHtml(u.username||"Discord User")+'</span>':'<span>'+escapeHtml(u.username||"Discord User")+'</span>');$("loginBtn").classList.add("logged-in");$("username").textContent=u.username||"Discord User";$("userid").textContent=u.id||"";
 if(u.avatar){$("avatar").src=u.avatar;$("avatar").classList.remove("hidden")}else $("avatar").classList.add("hidden");
 const badges=[];const rb=u.roleBadges||{};if(rb.founder)badges.push('<span class="role-badge founder">Founder</span>');else if(rb.staff||u.isStaff)badges.push('<span class="role-badge staff">Staff</span>');if(rb.premium)badges.push('<span class="role-badge premium">Premium</span>');$("roleBadges").innerHTML=badges.join("");
 $("staffSwitchWrap").classList.toggle("hidden",!u.isStaff);$("staffTab").classList.toggle("hidden",!u.isStaff);$("deleteAllBtn").classList.toggle("hidden",!(u.isFounder||u.isAdmin));
 $("staffSwitch").checked=false;updateStaffMode(false);
}
function updateStaffMode(on){if(!currentUser?.isStaff)on=false;document.body.classList.toggle("staff-mode",on);$("staffTab").classList.toggle("hidden",!on);$("blacklistSideTab").classList.toggle("hidden",!on);if(on&&currentTicket){const t=ticketCache.find(x=>x.id===currentTicket)||staffCache.find(x=>x.id===currentTicket);if(t)renderActions(t);}if(!on){$("chatActions").innerHTML="";if(!$("staffView").classList.contains("hidden")||!$("blacklistView").classList.contains("hidden"))setView("tickets");else if(currentTicket&&!$("chat").classList.contains("hidden")){$("chatActions").innerHTML="";}}}
function setView(v){["ticketListView","newTicketView","staffView","chat"].forEach(x=>$(x).classList.add("hidden"));["ticketsTab","newTicketTab","staffTab","blacklistSideTab"].forEach(x=>$(x).classList.remove("active"));$("blacklistView").classList.add("hidden");$("staffQueueHead").classList.remove("hidden");$("staffFilters").classList.remove("hidden");if(v==="tickets"){$("ticketListView").classList.remove("hidden");$("ticketsTab").classList.add("active");loadTickets()}if(v==="new"){$("newTicketView").classList.remove("hidden");$("newTicketTab").classList.add("active")}if(v==="staff"){$("staffView").classList.remove("hidden");$("staffTab").classList.add("active");$("staffTickets").classList.remove("hidden");loadStaffTickets()}if(v==="blacklist"){$("blacklistView").classList.remove("hidden");$("blacklistSideTab").classList.add("active");loadBlacklist()}if(v==="chat")$("chat").classList.remove("hidden");}
function ticketHtml(t,staff=false){const owner=t.owner||{};const claimed=t.claimedBy;return '<div class="ticketCard"><button class="ticketMain" data-id="'+escapeHtml(t.id)+'"><img src="'+escapeHtml(owner.avatar||"")+'" onerror="this.style.display=\'none\'"><div class="ticketInfo"><b>'+escapeHtml(t.name)+'</b><span>'+escapeHtml(t.category||"Other")+' · '+escapeHtml(t.status)+'</span><small>'+escapeHtml(owner.username||"")+(owner.id?" · "+escapeHtml(owner.id):"")+(claimed?" · Claimed by @"+escapeHtml(claimed.username):"")+'</small></div><span class="status '+escapeHtml(t.status)+'">'+escapeHtml(t.status)+'</span></button>'+ (staff?'<button class="tab claimCardBtn" data-claim="'+escapeHtml(t.id)+'">'+(claimed?"Unclaim":"Claim")+'</button><button class="miniDelete" data-delete="'+escapeHtml(t.id)+'">Delete</button>':"")+'</div>';}
async function loadTickets(){try{const ts=await api("/api/tickets");ticketCache=ts;$("tickets").innerHTML=ts.length?ts.map(t=>ticketHtml(t)).join(""):"No tickets yet.";bindTicketButtons($("tickets"));}catch(e){$("tickets").textContent="Could not load tickets: "+e.message;}}
function bindTicketButtons(box){box.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openTicket(b.dataset.id));box.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteTicket(b.dataset.delete));box.querySelectorAll("[data-claim]").forEach(b=>b.onclick=async(e)=>{e.stopPropagation();try{await api("/api/tickets/"+b.dataset.claim+"/"+(b.textContent.trim()==="Unclaim"?"unclaim":"claim"),{method:"POST",body:"{}"});await loadStaffTickets();if(currentTicket===b.dataset.claim)await openTicket(currentTicket);}catch(err){alert(err.message)}});}
async function loadStaffTickets(){try{staffCache=await api("/api/staff/tickets");renderStaff();}catch(e){$("staffTickets").textContent="Could not load staff tickets: "+e.message;}}
function renderStaff(){const q=$("staffSearch").value.trim().toLowerCase(),cat=$("staffCategory").value,status=$("staffStatus").value;const list=staffCache.filter(t=>(!cat||t.category===cat)&&(!status||t.status===status)&&(!q||[t.name,t.category,t.status,t.topic,t.owner?.username,t.owner?.id].some(x=>String(x||"").toLowerCase().includes(q))));$("staffTickets").innerHTML=list.length?list.map(t=>ticketHtml(t,true)).join(""):"No matching tickets.";bindTicketButtons($("staffTickets"));}
async function openTicket(id){
  currentTicket=id;setView("chat");$("chatTitle").textContent="Loading...";$("chatActions").innerHTML="";
  try{
    const t=ticketCache.find(x=>x.id===id)||staffCache.find(x=>x.id===id);
    if(t){$("chatTitle").textContent=t.name;$("chatMeta").textContent=(t.category||"Other")+" · "+t.status+(t.claimedBy?" · Claimed by @"+t.claimedBy.username:"");renderActions(t);}
    await loadMessages(id);
  }catch(e){$("chatTitle").textContent="Ticket";$("messages").textContent=e.message;}
}
function renderActions(t){if(!currentUser?.isStaff||!$("staffSwitch").checked)return;const actions=[[t.status==="claimed"?"unclaim":"claim",t.status==="claimed"?"Unclaim":"Claim"],["accept","Accept"],["decline","Decline"],["close","Close"],["reopen","Reopen"],["rename","Rename"],["blacklist","Blacklist"],["delete","Delete"]];$("chatActions").innerHTML=actions.map(a=>'<button class="'+(a[0]==="delete"?"danger":"tab")+'" data-action="'+a[0]+'">'+a[1]+'</button>').join("");$("chatActions").querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>ticketAction(b.dataset.action));}
async function loadMessages(id,stick=true){if(refreshingMessages)return;refreshingMessages=true;try{const nearBottom=$("messages").scrollHeight-$("messages").scrollTop-$("messages").clientHeight<100;const ms=await api("/api/tickets/"+id+"/messages");renderMessages(ms,stick||nearBottom);}catch(e){if(/Ticket not found/i.test(e.message)){currentTicket=null;setView(currentUser?.isStaff?"staff":"tickets");}else throw e;}finally{refreshingMessages=false;}}
function renderMessages(ms,stick=true){$("messages").innerHTML=ms.map(m=>'<div class="msgRow '+(m.discordId===currentUser?.id?"mine":"")+'"><img src="'+escapeHtml(m.avatar||"")+'" onerror="this.style.display=\'none\'"><div class="msgBody"><div class="msgHeader"><b>'+escapeHtml(m.author)+'</b><small>'+new Date(m.createdAt).toLocaleString()+'</small></div><div class="msgText">'+escapeHtml(m.content)+'</div>'+(m.attachment?'<a class="attachment" target="_blank" href="'+escapeHtml(m.attachment.data)+'" download="'+escapeHtml(m.attachment.name)+'">'+escapeHtml(m.attachment.name)+'</a>':"")+'</div></div>').join("")||'<div class="emptyChat">No messages yet.</div>';$("messages").scrollTop=$("messages").scrollHeight;}
async function ticketAction(action){if(!currentTicket)return;if(!currentUser?.isStaff||!$("staffSwitch").checked)return;if(action==="delete"&&!confirm("Delete this ticket permanently?"))return;let body={};if(action==="rename"){const current=($("chatTitle").textContent||"").trim();const name=prompt("Rename ticket:",current);if(name===null)return;const clean=name.trim();if(!clean)return;body={name:clean}}try{await api("/api/tickets/"+currentTicket+"/"+action,{method:"POST",body:JSON.stringify(body)});if(action==="delete"){currentTicket=null;setView(currentUser?.isStaff?"staff":"tickets");return;}await openTicket(currentTicket);if(currentUser?.isStaff)loadStaffTickets();}catch(e){alert(e.message)}}
async function deleteTicket(id){if(!confirm("Delete this ticket permanently?"))return;try{await api("/api/tickets/"+id+"/delete",{method:"POST",body:"{}"});await loadStaffTickets()}catch(e){alert(e.message)}}
function renderBlacklist(){const xs=blacklistCache;const q=($("blackSearch")?.value||"").trim().toLowerCase();const filtered=xs.filter(x=>!q||String(x.discord_username||"").toLowerCase().includes(q)||String(x.discord_user_id||"").includes(q)||String(x.reason||"").toLowerCase().includes(q));$("blacklistItems").innerHTML=filtered.length?filtered.map(x=>{const exp=x.expires_at?new Date(x.expires_at).toLocaleString():"Permanent";return '<div class="blackRow"><div><b>'+escapeHtml(x.discord_username||x.discord_user_id)+'</b><small>'+escapeHtml(x.discord_user_id)+' · '+escapeHtml(x.reason||"No reason")+' · '+escapeHtml(exp)+'</small></div><button class="tab" data-unblack="'+escapeHtml(x.discord_user_id)+'">Remove</button></div>'}).join(""):(q?"No matching blacklisted members.":"No blacklisted users.");$("blacklistItems").querySelectorAll("[data-unblack]").forEach(b=>b.onclick=async()=>{try{await api("/api/blacklist/"+b.dataset.unblack,{method:"DELETE"});await loadBlacklist()}catch(e){alert(e.message)}})}
async function loadBlacklist(){try{blacklistCache=await api("/api/blacklist");renderBlacklist()}catch(e){$("blacklistItems").textContent=e.message}}
$("loginBtn").onclick=()=>{if(!currentUser)location.href=API_BASE+"/auth/discord"};$("blacklistSideTab").onclick=()=>{if(currentUser?.isStaff&&$("staffSwitch").checked)setView("blacklist")};$("openBtn").onclick=async()=>{try{if(!currentUser)showUser(await api("/api/me"));$("home").classList.add("hidden");setView("new");$("app").scrollIntoView({behavior:"smooth"})}catch{location.href=API_BASE+"/auth/discord"}};$("ticketsTab").onclick=()=>setView("tickets");$("newTicketTab").onclick=()=>setView("new");$("staffTab").onclick=()=>{if(currentUser?.isStaff&&$("staffSwitch").checked)setView("staff")};$("staffSwitch").onchange=()=>updateStaffMode($("staffSwitch").checked);$("backStaffBtn").onclick=()=>setView("staff");$("backBtn").onclick=()=>setView(currentUser?.isStaff?"staff":"tickets");$("logoutBtn").onclick=()=>{localStorage.removeItem("socce7ball_access_token");accessToken="";location.href=API_BASE+"/auth/logout"};
$("submitBtn").onclick=async()=>{const s=$("status");if(sending)return;sending=true;$("submitBtn").disabled=true;s.textContent="Creating ticket...";try{const r=await api("/api/tickets",{method:"POST",body:JSON.stringify({category:$("category").value,topic:$("topic").value,message:$("message").value})});s.textContent="Ticket created";$("message").value="";$("topic").value="";await loadTickets();await openTicket(r.ticketId)}catch(e){s.textContent="Error: "+e.message}finally{sending=false;$("submitBtn").disabled=false}};
$("sendBtn").onclick=async()=>{
  if(sending)return;
  const id=currentTicket,v=$("chatInput").value.trim(),file=$("fileInput").files[0];
  if(!id||(!v&&!file))return;
  sending=true;$("sendBtn").disabled=true;
  try{
    let attachment=null;
    if(file){
      if(file.size>2*1024*1024)throw Error("File must be 2 MB or smaller.");
      attachment={name:file.name,type:file.type||"application/octet-stream",data:await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})};
    }
    const optimistic={discordId:currentUser?.id,author:currentUser?.username||"You",avatar:currentUser?.avatar||"",content:v,createdAt:new Date().toISOString(),attachment};
    const existing=[...$("messages").querySelectorAll(".msgRow")];
    if(existing.length&&existing[0].querySelector(".emptyChat"))$("messages").innerHTML="";
    const row=document.createElement("div");row.className="msgRow mine";
    row.innerHTML='<img src="'+escapeHtml(optimistic.avatar)+'"><div class="msgBody"><div class="msgHeader"><b>'+escapeHtml(optimistic.author)+'</b><small>Sending…</small></div><div class="msgText">'+escapeHtml(optimistic.content)+'</div>'+(attachment?'<span class="attachment">'+escapeHtml(attachment.name)+'</span>':"")+'</div>';
    $("messages").appendChild(row);$("messages").scrollTop=$("messages").scrollHeight;
    $("chatInput").value="";$("fileInput").value="";$("fileName").textContent="";
    await api("/api/tickets/"+id+"/messages",{method:"POST",body:JSON.stringify({message:v,attachment})});
    await loadMessages(id,true);
  }catch(e){await loadMessages(id,true).catch(()=>{});alert(e.message)}
  finally{sending=false;$("sendBtn").disabled=false}
};
$("attachBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=()=>{$("fileName").textContent=$("fileInput").files[0]?.name||""};["staffSearch","staffCategory","staffStatus"].forEach(id=>$(id).oninput=renderStaff);$("blackSearch")?.addEventListener("input",()=>{clearTimeout(blacklistSearchTimer);blacklistSearchTimer=setTimeout(renderBlacklist,120)});$("addBlacklistBtn").onclick=async()=>{const userId=$("blackUserId").value.trim(),durationHours=Number($("blackDuration").value),reason=$("blackReason").value.trim();if(!userId){alert("Discord User ID required");return}try{await api("/api/blacklist",{method:"POST",body:JSON.stringify({userId,durationHours,reason})});$("blackUserId").value="";$("blackReason").value="";await loadBlacklist()}catch(e){alert(e.message)}};$("deleteAllBtn").onclick=async()=>{if(!confirm("Delete ALL tickets permanently?"))return;try{await api("/api/tickets/delete-all",{method:"POST",body:"{}"});await loadStaffTickets()}catch(e){alert(e.message)}};
(async()=>{try{const health=await api("/health");setBotImage(health.botAvatar);const p=new URLSearchParams(location.search),handoff=p.get("auth");if(handoff){const r=await api("/auth/exchange",{method:"POST",body:JSON.stringify({token:handoff})});accessToken=r.token;localStorage.setItem("socce7ball_access_token",accessToken);history.replaceState({},document.title,location.pathname);showUser(r.user);setView("tickets");return}showUser(await api("/api/me"));setView("tickets")}catch{}})();
setInterval(()=>{if(currentTicket&&!$("chat").classList.contains("hidden"))loadMessages(currentTicket,false).catch(()=>{});else if(currentUser){if(!$("ticketListView").classList.contains("hidden"))loadTickets().catch(()=>{});else if(currentUser.isStaff&&$("staffSwitch").checked&&!$("blacklistView").classList.contains("hidden"))loadBlacklist().catch(()=>{});else if(currentUser.isStaff&&$("staffSwitch").checked&&!$("staffView").classList.contains("hidden"))loadStaffTickets().catch(()=>{});}},5000);
